version: '3'
services:
  product-app:
    container_name: product-app
    build: 
      context: ./product
      args:
        NODE_ENV: development
    ports:
      - "8000:8000"
    volumes:
      - ./product:/product/src:ro
      - /product/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
  order-app:
    container_name: order-app
    build: 
      context: ./order
      args:
        NODE_ENV: development
    ports:
      - "8001:8001"
    volumes:
      - ./order:/order/src:ro
      - /order/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8001
